name: .NET

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run:  dotnet restore ML_Bets/ML_Bets.sln
    - name: Build
      run: dotnet publish --no-restore ML_Bets/ML_Bets.sln -c Release -o release --nologo
    - name: Test
      run: dotnet test --no-build --verbosity normal
